export const REQUEST_GENERATE_AUTHORIZATION_URL =
  "http://ottapi.com/v1.7/ntm/index/generateauthorization?key=0tt@pi.C0m_Med1@&token=cab9f50230778df5c52b4ccb4d12d6ca";
export const REQUEST_HOME_URL = "http://ottapi.com/v1.7/ntm/home";
export const REQUEST_MENU_URL = "http://ottapi.com/v1.7/ntm/home/menu";
export const REQUEST_SEARCH_URL = "http://ottapi.com/v1.7/ntm/search";
export const REQUEST_DETAIL_URL = "http://ottapi.com/v1.7/ntm/detail/index";
export const REQUEST_CATEGORY_URL =
  "http://ottapi.com/v1.7/ntm/contentgroup/index";
export const REQUEST_PACKAGE_LIST_PAYMENT_URL =
  "http://ottapi.com/v1.7/ntm/package/listpayment";
export const REQUEST_PACKAGE_MY_CONTENTS_URL =
  "http://ottapi.com/v1.7/ntm/package/mycontents";
export const REQUEST_PACKAGE_LIST_ALL_URL =
  "http://ottapi.com/v1.7/ntm/package/listall";
export const REQUEST_PACKAGE_LIST_CONTENT_BY_PACKAGE =
  "http://ottapi.com/v1.7/ntm/package/listcontentbypackage/?pk_id=";
export const REQUEST_PAYMENT_SUCCESS_URL =
  "http://ottapi.com/v1.7/ntm/payment/success";
export const REQUEST_PAYMENT_PROMOTION_URL =
  "http://ottapi.com/v1.7/ntm/payment/promotion/?proCode=";
export const REQUEST_LOGIN_URL = "http://ottapi.com/v1.7/ntm/login/";
export const REQUEST_FB_LOGIN_URL = "http://ottapi.com/v1.7/ntm/fblogin";
export const REQUEST_REGISTER_URL =
  "http://ottapi.com/v1.7/ntm/member/register";
export const REQUEST_FORGOT_PASSWORD_URL =
  "http://sbtnapp.com/en/user/forgot_password";
export const REQUEST_URL_LIST_CATEGORIES =
  "http://ottapi.com/v1.7/ntm/contentgroup/index/";

export const REQUEST_URL_PLAYLIST = "http://ottapi.com/v1.7/ntm/playlist/";
export const REQUEST_URL_ADD_EDIT_PLAYLIST =
  "http://ottapi.com/v1.7/ntm/playlist/addedit/";
export const REQUEST_URL_DELETE_PLAYLIST =
  "http://ottapi.com/v1.7/ntm/playlist/delete";
export const REQUEST_URL_PLAYLIST_ADD_CONTENT =
  "http://ottapi.com/v1.7/ntm/playlist/addcontent/";
export const REQUEST_URL_CONTENT_PLAYLIST =
  "http://ottapi.com/v1.7/ntm/playlist/detail";

///////////////////////
// constants
///////////////////////

/****======== FETCHING HOME ==============***/

export const FETCHING_DATA = "FETCHING_DATA";
export const FETCHING_DATA_SUCCESS = "FETCHING_DATA_SUCCESS";
export const FETCHING_DATA_FAILURE = "FETCHING_DATA_FAILURE";

/****======== END FETCHING MENU ==============***/

/****======== FETCHING MENU ==============***/

export const FETCHING_DATA_MENU = "FETCHING_DATA_MENU";
export const FETCHING_DATA_MENU_SUCCESS = "FETCHING_DATA_MENU_SUCCESS";
export const FETCHING_DATA_MENU_FAILURE = "FETCHING_DATA_MENU_FAILURE";

/****======== END FETCHING MENU ==============***/

export const FETCHING_DATA_HOME = "FETCHING_DATA_HOME";
export const FETCHING_DATA_HOME_SUCCESS = "FETCHING_DATA_HOME_SUCCESS";
export const FETCHING_DATA_HOME_FAILURE = "FETCHING_DATA_HOME_FAILURE";
export const FETCHING_DATA_HOME_DESTROY = "FETCHING_DATA_HOME_DESTROY";
export const LEAVE_HOME_VIEW = "LEAVE_HOME_VIEW";
export const ENTER_PACKAGE_VIEW = "ENTER_PACKAGE_VIEW";
export const ENTER_PACKAGE_SUCCESS = "ENTER_PACKAGE_SUCCESS";
export const ENTER_PACKAGE_FAILURE = "ENTER_PACKAGE_FAILURE";
export const LEAVE_PACKAGE_VIEW = "LEAVE_PACKAGE_VIEW";
export const FETCHING_DATA_CATEGORY = "FETCHING_CATEGORY";
export const FETCHING_DATA_CATEGORY_SUCCESS = "FETCHING_CATEGORY_SUCCESS";
export const FETCHING_DATA_CATEGORY_FAILURE = "FETCHING_CATEGORY_FAILURE";
export const ENTER_GROUP_CATEGORY_VIEW = "ENTER_GROUP_CATEGORY_VIEW";
export const ENTER_GROUP_CATEGORY_SUCCESS = "ENTER_GROUP_CATEGORY_SUCCESS";
export const ENTER_GROUP_CATEGORY_FAILURE = "ENTER_GROUP_CATEGORY_FAILURE";
export const ENTER_GROUP_CATEGORY_DESTROY = "ENTER_GROUP_CATEGORY_DESTROY";
export const LEAVE_CATEGORY_VIEW = "LEAVE_CATEGORY_VIEW";
export const ENTER_SEARCH_VIEW = "ENTER_SEARCH_VIEW";
export const ENTER_SEARCH_SUCCESS = "ENTER_SEARCH_SUCCESS";
export const ENTER_SEARCH_FAILURE = "ENTER_SEARCH_FAILURE";
export const ENTER_SEARCH_DESTROY = "ENTER_SEARCH_DESTROY";
export const LEAVE_SEARCH_VIEW = "LEAVE_SEARCH_VIEW";
export const ENTER_DETAIL_VIEW = "ENTER_DETAIL_VIEW";
export const FETCHING_DATA_DETAIL = "FETCHING_DATA_DETAIL";
export const FETCHING_DATA_DETAIL_SUCCESS = "FETCHING_DATA_DETAIL_SUCCESS";
export const FETCHING_DATA_DETAIL_FAILURE = "FETCHING_DATA_DETAIL_FAILURE";
export const FETCHING_FULL_SCREEN = "FETCHING_FULL_SCREEN";

export const LEAVE_DETAIL_VIEW = "LEAVE_DETAIL_VIEW";
export const ENTER_LOGIN_VIEW = "ENTER_LOGIN_VIEW";
export const ENTER_LOGIN_SUCCESS = "ENTER_LOGIN_SUCCESS";
export const ENTER_LOGIN_FAILURE = "ENTER_LOGIN_FAILURE";
export const LEAVE_LOGIN_VIEW = "LEAVE_LOGIN_VIEW";
export const ENTER_LOGOUT_VIEW = "ENTER_LOGOUT_VIEW";
export const ENTER_LOGOUT_SUCCESS = "ENTER_LOGOUT_SUCCESS";
export const ENTER_LOGOUT_FAILURE = "ENTER_LOGOUT_FAILURE";
export const ENTER_REGISTER_VIEW = "ENTER_REGISTER_VIEW";
export const ENTER_REGISTER_SUCCESS = "ENTER_REGISTER_SUCCESS";
export const ENTER_REGISTER_FAILURE = "ENTER_REGISTER_FAILURE";
export const ENTER_REGISTER_DESTROY = "ENTER_REGISTER_DESTROY";
export const LEAVE_REGISTER_VIEW = "LEAVE_REGISTER_VIEW";

export const FETCHING_DATA_AUDIO = "FETCHING_DATA_AUDIO";
export const FETCHING_DATA_AUDIO_SUCCESS = "FETCHING_DATA_AUDIO_SUCCESS";
export const FETCHING_DATA_AUDIO_FAILURE = "FETCHING_DATA_AUDIO_FAILURE";
export const LEAVE_AUDIO_VIEW = "LEAVE_AUDIO_VIEW";

export const ENTER_PLAYLIST_VIEW = "ENTER_PLAYLIST_VIEW";
export const ENTER_PLAYLIST_SUCCESS = "ENTER_PLAYLIST_SUCCESS";
export const ENTER_PLAYLIST_FAILURE = "ENTER_PLAYLIST_FAILURE";
export const ENTER_PLAYLIST_DESTROY = "ENTER_PLAYLIST_DESTROY";

export const ENTER_ADD_PLAYLIST_SUCCESS = "ENTER_ADD_PLAYLIST_SUCCESS";
export const ENTER_ADD_PLAYLIST_FAILURE = "ENTER_ADD_PLAYLIST_FAILURE";
export const ENTER_DESTROY_ADD_PLAYLIST_SUCCESS =
  "ENTER_DESTROY_ADD_PLAYLIST_SUCCESS";
export const ENTER_DELETE_PLAYLIST_SUCCESS = "ENTER_DELETE_PLAYLIST_SUCCESS";
export const ENTER_DELETE_PLAYLIST_FAILURE = "ENTER_DELETE_PLAYLIST_FAILURE";

export const ENTER_UPDATE_PLAYLIST_SUCCESS = "ENTER_UPDATE_PLAYLIST_SUCCESS";
export const ENTER_UPDATE_PLAYLIST_FAILURE = "ENTER_UPDATE_PLAYLIST_FAILURE";

export const ENTER_CONTENT_PLAYLIST_VIEW = "ENTER_CONTENT_PLAYLIST_VIEW";
export const ENTER_CONTENT_PLAYLIST_SUCCESS = "ENTER_CONTENT_PLAYLIST_SUCCESS";
export const ENTER_CONTENT_PLAYLIST_FAILURE = "ENTER_CONTENT_PLAYLIST_FAILURE";
export const ENTER_DESTROY_CONTENT_PLAYLIST_SUCCESS =
  "ENTER_DESTROY_CONTENT_PLAYLIST_SUCCESS";
export const ENTER_DESTROY_DELETE_PLAYLIST = "ENTER_DESTROY_DELETE_PLAYLIST";

export const ENTER_PLAYLIST_ADD_CONTENT_SUCCESS =
  "ENTER_PLAYLIST_ADD_CONTENT_SUCCESS";
export const ENTER_PLAYLIST_ADD_CONTENT_FAILURE =
  "ENTER_PLAYLIST_ADD_CONTENT_FAILURE";

export const CHANGE_ACTIVE_PLAYLIST = "CHANGE_ACTIVE_PLAYLIST";
export const CHANGE_ACTIVE_SONG_ID = "CHANGE_ACTIVE_SONG_ID";
export const CHANGE_ACTIVE_USER_ID = "CHANGE_ACTIVE_USER_ID";
export const CHANGE_CURRENT_TIME = "CHANGE_CURRENT_TIME";
export const CHANGE_HEIGHT = "CHANGE_HEIGHT";
export const CHANGE_PATH = "CHANGE_PATH";
export const CHANGE_PLAYING_SONG = "CHANGE_PLAYING_SONG";
export const CHANGE_SELECTED_PLAYLISTS = "CHANGE_SELECTED_PLAYLISTS";
export const PLAY_SONG = "PLAY_SONG";
export const RECEIVE_SONG = "RECEIVE_SONG";
export const RECEIVE_SONG_COMMENTS = "RECEIVE_SONG_COMMENTS";
export const RECEIVE_SONGS = "RECEIVE_SONGS";
export const RECEIVE_USER = "RECEIVE_USER";
export const RECEIVE_USER_FOLLOWINGS = "RECEIVE_USER_FOLLOWINGS";
export const RECEIVE_USER_PROFILES = "RECEIVE_USER_PROFILES";
export const REQUEST_SONG = "REQUEST_SONG";
export const REQUEST_SONGS = "REQUEST_SONGS";
export const REQUEST_USER = "REQUEST_USER";
export const CHANGE_PLAYLIST = "CHANGE_PLAYLIST";
export const CHANGE_PLAYER_STATUS = "CHANGE_PLAYER_STATUS";
export const CHANGE_PLAYER_REPEAT_NUMBER = "CHANGE_PLAYER_REPEAT_NUMBER";
export const CHANGE_CURRENT_ITEM_PLAY = "CHANGE_CURRENT_ITEM_PLAY";
export const CHANGE_RANDOM_STATUS = "CHANGE_RANDOM_STATUS";
export const CHANGE_TYPES = {
  NEXT: "NEXT",
  PLAY: "PLAY",
  SHUFFLE: "SHUFFLE"
};
export const PLAY_STATUS = {
  INIT: "INIT",
  PLAYING: "PLAYING",
  PAUSED: "PAUSED",
  END: "END"
};
