# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ASIA' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ASIA

 pod 'google-cast-sdk', '2.10.4.1'
end
